org.gradle.jvmargs=-Xmx8G -Xms2G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.vfs.watch=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.1
loader_version=1.20.1-47.4.3
#Fabric api
fabric_version=3.3.6+631c9cd677
# Mod Properties
mod_version=0.12.4
maven_group=me.jellysquid.mods

loom.platform=forge
